### ISSUE TITLE
Eliminate `envkey` from `get_data_dir`?

### ISSUE THREAD

**Issue by laserson** [hammerlab/datacache#9]
What is the use case for `envkey` in `get_data_dir`?

https://github.com/hammerlab/datacache/blob/master/datacache/common.py#L29

It doesn't seem to be used anywhere in the repo, nor in pyensembl, for instance.

**Comment by iskandr** [comment]
I used once to configure which local files to use for IEDB sources but I don't think it's been used since and doesn't actually make too much sense here. I'm happy to remove it.

**Comment by iskandr** [comment]
Now getting used for defining pyensembl data directories.
